When a test passes despite being expected to fail (marked with
  pytest.mark.xfail), itâ€™s an xpass and will be reported in the test summary.