Passing from_pt=True to this method will throw an exception.